name: mammo_classifier
path_to_mammoclip_ckpt: ${PATHS.path_to_mammoclip_ckpt}
_class:
  _target_: source.models.mammo_classifier.MammoClassifier
  vision_encoder: ${MODEL.vision_encoder}
  classifier: ${MODEL.classifier_layer}
  ckpt_clip: ${MODEL.path_to_mammoclip_ckpt}
  image_global_feat_dim: 1408
  embed_dim: 512
  freeze_projection: true

vision_encoder:
  _target_: source.models.vision_efficientnet.VisionEfficientNet
  lora: ${TUNE.use_lora}
  ckpt_clip: ${MODEL.path_to_mammoclip_ckpt}
  vision_encoder: ${MODEL.visual_efficientnet}
  lora_r: ${TUNE.lora.r}
  lora_alpha_mult: ${TUNE.lora.alpha_mult}
  lora_dropout: ${TUNE.lora.dropout}
  lora_target_modules: ${TUNE.lora.target_modules}

visual_efficientnet:
  _target_: source.models.efficientnet.EfficientNet.from_pretrained
  model_name: "efficientnet-b2"
  num_classes: 1

classifier_layer:
  _target_: ${CLASSIFIER._target_}
  num_class: ${TASK.num_classes}
  feature_dim: ${MODEL._class.embed_dim}  # embed_dim, output of projection